---
title: "Evolution of regulatory networks controlling plasticity in gene expression between Saccharomyces yeast"
---

Code used in Redhuis et al. "Evolution of regulatory networks controlling plasticity in gene expression between Saccharomyces yeast". Scripts are organized into 3 categories: 1) Data cleaning, 2) Data analysis, 3) Figures for paper

Following this tutorial: https://rstudio4edu.github.io/rstudio4edu-book/make-rmd.html

## Abstract

Organisms often cope with changes in their environments by modifying gene expression levels, which can affect their cellular function. This plasticity in gene expression arises when cells sense a change in their environment and alter the activity or availability of trans-regulatory factors, which interact with each gene’s cis-regulatory sequences to determine its expression. To understand how regulatory networks controlling plasticity in gene expression evolve, we used RNAseq data from the baker’s yeast Saccharomyces cerevisiae, its close relative Saccharomyces paradoxus, and their F1 hybrids collected at multiple time points following the transfer of cells from standard laboratory conditions to five different environments (low phosphorus, low nitrogen, hydroxyurea shock, heat stress, and cold stress. We also looked at how gene expression changes during the transition from log phase to stationary phase. In all six datasets, we compared gene expression levels between S. cerevisiae and S. paradoxus and asked how expression plasticity has diverged. We then tested for divergence in expression plasticity between the two species-specific alleles in F1 hybrids, allowing us to disentangle the effects of divergence in cis- and trans-regulation. In all 6 environments, we found at least 100 genes showing divergence in expression plasticity between species. Most cases were unique to a single environment and attributable primarily to trans-regulatory divergence. Our work demonstrates how comparing species in diverse environments and multiple timepoints can reveal hidden dimensions of gene expression divergence.
