---
title: 'QC: Signal to Noise vs Dispersion'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r environment-setup}
source("functions_for_figure_scripts.R")
library("pheatmap")
load("data_files/FinalDataframe3Disp.RData")
snrdf <- read_csv("data_files/QC_signal-to-noise.csv")
```
Discrete heatmaps of genes assigned to 0 cluster using different thresholds/criteria.

Comparing the main paper's cluster criterion of Disp = 3 versus each version of signal to noise to find the one that is most similar to Disp = 3 assignments

```{r discrete-heatmap-lowly-varying}
plot_mat <- finaldf |> dplyr::select(gene_name, experiment, cer, par) |> 
  pivot_longer(cols = c("cer", "par"),
               names_to = "species",
               values_to = "Disp3") |> 
  left_join(snrdf, by = c("gene_name"="gene_ID", "experiment", "species"))
colnames_plotmat <- paste(plot_mat$gene_name, plot_mat$species, 
                          plot_mat$experiment, sep = "_")
rownames_plotmat <- colnames(plot_mat)
plot_mat <- data.frame(plot_mat) |> t()
colnames(plot_mat) <- colnames_plotmat
rownames(plot_mat) <- rownames_plotmat
plot_mat <- plot_mat[!(rownames(plot_mat) %in% c("gene_name", "experiment", "species")),]
plot_mat <- plot_mat |> as.matrix()
mode(plot_mat) <- "numeric"
plot_mat[is.na(plot_mat)] <- 1 # currently only 1 NA value: YPR148C, Heat, cer, SNR 1pct
plot_mat[plot_mat != 0] <- 1
clrs <- structure(c("grey", "red"), 
                  names = c(1, 0))
# sorting cols by Disp3's order
col_order_vec <- order(factor(plot_mat["Disp3",], levels = c(1, 0)))

# ordering full plotmat
ordered_plot_mat <- orderGenesByGroup(.mat = plot_mat[c("Disp3", "SNR_30pct"),], .labels = c(1, 0))
rownames(ordered_plot_mat) <- c("Disp3", "SNR_30pct")
pheatmap(ordered_plot_mat, cluster_rows = FALSE, cluster_cols = FALSE, show_colnames = FALSE)
```

4-group comparison between Disp3 and signal-to-noise 30%:

```{r discrete-heatmap-group4, cache=TRUE}
plotdf <- finaldf |> dplyr::select(gene_name, experiment, group4) |> 
  dplyr::rename(c("group4_disp3"="group4"))
load("data_files/FinalDataframe_SNR30pct.RData")
plotdf <- left_join(plotdf, select(finaldf, gene_name, experiment, group4), by = c("gene_name", "experiment")) |> 
  dplyr::rename(c("group4_SNR30pct"="group4"))
plot_mat <- select(plotdf, group4_disp3, group4_SNR30pct) |> t() |> as.matrix()
ordered_plot_mat <- orderGenesByGroup(.mat = plot_mat)
rownames(ordered_plot_mat) <- c("Dispersion 3", "Signal-to-noise 30%")
plotdf <- map(c("Dispersion 3", "Signal-to-noise 30%"), \(e) {
  idx <- which(c("Dispersion 3", "Signal-to-noise 30%") == e)
  return(tibble(gene_name = colnames(ordered_plot_mat),
                environment = e,
                group4 = ordered_plot_mat[idx,],
                x = c(1:ncol(ordered_plot_mat)),
                y = c(length(LongExperimentNames):1)[idx])) # descending from top
}) |> purrr::reduce(.f = bind_rows)
p <- ggplot(plotdf, aes(x = x, y = y, fill = group4)) +
  geom_tile_pattern(aes(fill = group4, pattern = group4), pattern_fill = "black",
                    pattern_density = 0.05, pattern_size = 0.05) +
  scale_fill_discrete(limits = colordf[colordf$scheme == "group4",]$limits,
                      type = colordf[colordf$scheme == "group4",]$type) +
  scale_pattern_discrete(limits = colordf[colordf$scheme == "group4",]$limits,
                         choices = colordf[colordf$scheme == "group4",]$pattern) +
  theme_void()
p
```

